overrides:
  - files:
      - '**/*.scss'
    customSyntax: 'postcss-scss'
    plugins:
      - stylelint-scss

extends:
  - stylelint-config-recommended
  - stylelint-prettier/recommended

plugins:
  - stylelint-order

rules:
  at-rule-no-unknown: null
  no-descending-specificity: null
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - 'global'

  order/order:
    - 'custom-properties'
    - 'declarations'
  order/properties-order:
    - groupName: 'positioning'
      properties:
        - 'content'
        - 'position'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'
        - 'display'
        - 'float'
        - 'overflow'
        - 'clear'
        - 'z-index'
    - groupName: 'box'
      properties:
        - 'width'
        - 'min-width'
        - 'max-width'
        - 'height'
        - 'min-height'
        - 'max-height'
        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'
        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'
        - 'border'
        - 'background'
    - groupName: 'font'
      properties:
        - 'font-family'
        - 'font-size'
        - 'font-style'
        - 'font-weight'
        - 'font-variant'
        - 'line-height'
        - 'color'
    - groupName: 'text'
      properties:
        - 'text-align'
        - 'vertical-align'
        - 'text-wrap'
        - 'text-transform'
        - 'text-indent'
        - 'text-decoration'
        - 'letter-spacing'
        - 'word-spacing'
        - 'white-space'
        - 'text-overflow'
    - groupName: 'other'
      properties:
        - 'box-shadow'
        - 'border-radius'
        - 'transform'
